git:
    submodules: false

before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

language: c

compiler: gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-7
            - make

script:
    - ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
    - export CC=/usr/bin/gcc-7
    - gcc -v && g++ -v && cmake --version

jobs:
    include:
        - stage: compile
          script: make -J4
stages:
    - compile 
